### ISSUE TITLE
Error upon direct usage

### ISSUE THREAD

**Issue by CaliCastle** [TerryZ/v-region#13]
![image](https://user-images.githubusercontent.com/10830749/48746451-47a87400-ec24-11e8-8c6d-fc376fe31277.png)

Thanks for the library! But I just got an error message when I tried to use it in my project, if you can take a look that'll be helpful!

I'm assuming that this error has something to do with the `v-dropdown` dependency, but I'm not sure at this point on how exactly to fix it, and this error message popped up after I imported the package and:
```js
import vRegion from 'v-region';

Vue.use(vRegion);
```

in the Vue file:
```vue
<v-region :ui="true" />
```

**Comment by TerryZ** [comment]
What browser are you using?

**Comment by CaliCastle** [comment]
@TerryZ Chrome Canary
Version 72.0.3615.0 (Official Build) canary (64-bit)

**Comment by TerryZ** [comment]
This is incredible, the best effect of the plugin is Chrome. Have you tried other browsers?

The last release version is 70.0.3538.110 of Chrome in my computer.....

**Comment by TerryZ** [comment]
May be your environment have some special stuff, that is my thought.

No one else have this issues so far.

**Comment by TerryZ** [comment]
I will keep eye on this issues.

**Comment by CaliCastle** [comment]
感谢

**Comment by CaliCastle** [comment]
I fixed it by manually editing the compiled js file (in `v-region/dist/v-region.js` and replaced `Event.prototype` with `Event.__proto__`

**Comment by TerryZ** [comment]
The plugin whether running correct or not in [Demo Page](https://terryz.github.io/vue/#/region/demo)

**Comment by CaliCastle** [comment]
@TerryZ not sure what you mean there

**Comment by CaliCastle** [comment]
@TerryZ the region dropdown works without an issue in your demo page

**Comment by TerryZ** [comment]
So i think there is some problem with your project environment.

**Comment by CaliCastle** [comment]
maybe but I'm using the default Laravel project, with laravel-mix and preset webpack config
