### ISSUE TITLE
如何自定义样式？

### ISSUE THREAD

**Issue by Leeero** [TerryZ/v-region#17]
在引入该组件后，无法自定义样式，例如选择器的高度，字体大小等等。并且通过设置
<v-region
            @values="selectLogs"
            class="xxxxxx"
  />

也无法重置样式。

**Comment by TerryZ** [comment]
每个插件都有自己设计标准的具体实现，如果它不满足你的需求，样式，字体大小高度等等问题，完全可以自行在页面上定义样式进行覆盖，达到自定义的需求
