### ISSUE TITLE
移动端页面面板偏移

### ISSUE THREAD

**Issue by Astrian** [TerryZ/v-region#18]
![image](https://user-images.githubusercontent.com/4896770/59734457-165c5900-9284-11e9-9a55-6f6589acf3cf.png)

**Comment by TerryZ** [comment]
目前不推荐使用在移动端

**Comment by Astrian** [comment]
@TerryZ 收到，感谢。目前用了比较低魔的 hack 方式来做兼容：

```
.v-dropdown-container {
    left: 16px !important;
  }
```

~~反正电脑上能看全就行了 23333~~
