### ISSUE TITLE
vue-element-admin中引入没有样式

### ISSUE THREAD

**Issue by CaiBaoHong** [TerryZ/v-region#2]
vue-element-admin中引入v-region没有样式，请问为什么会这样的？
![tim 20180614172547](https://user-images.githubusercontent.com/17343552/41403720-24a1b078-6ff8-11e8-9bc2-1c149d9eefc7.png)

**Comment by TerryZ** [comment]
你们本身 `<select>` 标签需要设置什么 class 它也设置什么 class

以 `Bootstrap3` 为例
```vue
<v-region class="form-control"></region>
```
