### ISSUE TITLE
当组件赋值一次之后，再赋值为null，打印出来的值是没有了，但是文本还是前一次的文本

### ISSUE THREAD

**Issue by gudufun** [TerryZ/v-region#21]
当组件赋值一次之后，再赋值为null，打印出来的值是没有了，但是文本还是前一次的文本

**Comment by TerryZ** [comment]
不可以把整个对象设置成 null

```vue
<template>
  <!-- 后续 selected 的入参会修改为 v-model  -->
  <region :selected="data">
  </region>
</template>

<script>
export default {
  ...
  data () {
    return {
      data: {
        province: null,
        city: null,
        area: null,
        town: null
      }
    }
  },
  methods: {
    doClear () {
      // ✖
      this.data = null
      // ✔
      this.data = {
        province: null,
        city: null,
        area: null,
        town: null
      }
    }
  }
}
</script>
```

**Comment by gudufun** [comment]
我在antd vue中使用了该组件，用v-decorator来进行表单验证，但是原生的v-region无法支持，我就在外面又包了一层。
按照邮件中的方法设置为null，依然存在值为空文本显示错误的问题。
而且，还有一个问题是，经常region控件会出现只显示市和区的问题，省没有文本显示。
请教下，可否提供下技术支持，有偿也可。谢谢！


这是我使用的办法。
<RegionSelect v-decorator="['startAddress', validatorRules.startAddress ]" :trigger-change="true" />
下面是我对v-region包了一层的代码。
<template>
  <div>
    <v-region :town="isHasTown" :ui="isUi" :selected="regionSelect" @values="regionChange" />
  </div>
</template>


<script>
export default {
  name: 'RegionSelect',
  props: {
    value: Object,
    triggerChange: Boolean,
    isUi: {
      type: Boolean,
      default: true
    },
    isHasTown: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      regionSelect: {}
    }
  },
  updated() {
    this.regionSelect = this.value
  },
  methods: {
    regionChange(val) {
      if (this.triggerChange) {
        this.$emit('change', val)
      } else {
        this.$emit('input', val)
      }
    }
  }
}
</script>



------------------ 原始邮件 ------------------
发件人: "Terry Zeng"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午5:04
收件人: "TerryZ/v-region"<v-region@noreply.github.com>;
抄送: "Only You。"<gudufun@vip.qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TerryZ/v-region] 当组件赋值一次之后，再赋值为null，打印出来的值是没有了，但是文本还是前一次的文本 (#21)




不可以把整个对象设置成 null
 <template>      <region :selected="data">   </region> </template> <script> export default {   ...   data () {     return {       data: {         province: null,         city: null,         area: null,         town: null       }     }   },   methods: {     doClear () {       // ✖       this.data = null       // ✔       this.data = {         province: null,         city: null,         area: null,         town: null       }     }   } } </script>

**Comment by TerryZ** [comment]
现有版本在数据变更后，部分情况下会有显示不正常的情况，所以这些处理变更的核心逻辑进行了重点重构

`v-region` 近期会发布一个重要的版本更新，目前已经进入单元测试阶段，如若功能不急，敬请期待新版本发布。另外，不需要偿技术支持，能有 star 或 follow 已然感谢。

**Comment by gudufun** [comment]
> 现有版本在数据变更后，部分情况下会有显示不正常的情况，所以这些处理变更的核心逻辑进行了重点重构
> 
> `v-region` 近期会发布一个重要的版本更新，目前已经进入单元测试阶段，如若功能不急，敬请期待新版本发布。另外，不需要偿技术支持，能有 star 或 follow 已然感谢。

大大牛逼！已star~感谢回复！

**Comment by TerryZ** [comment]
v-region `v2.2.2` 版本已发布，请更新使用，新版本应该可以解决你的问题，另外新版本在使用的参数上略有变化，请具体查看官网的 Demo 和 Changelog
