### ISSUE TITLE
下拉城市列表定位错误是怎么回事?

### ISSUE THREAD

**Issue by qq447665722** [TerryZ/v-region#25]
直接使用官网源码,但列表弹出定位的top计算错误
![image](https://user-images.githubusercontent.com/14967427/87540745-c512d900-c6d2-11ea-9212-1a72876190bb.png)

**Comment by qq447665722** [comment]
上下各加了一个有高度的div,用于测试

**Comment by TerryZ** [comment]
请更新最新版本
