### ISSUE TITLE
该项目中  是否支持 使用自定义的数据呢？使用我们接口中自己的数据 替代该项目中的 数据

### ISSUE THREAD

**Issue by WangMargin** [TerryZ/v-region#27]
该项目中  是否支持 使用自定义的数据呢？使用我们接口中自己的数据 替代该项目中的 数据

**Comment by TerryZ** [comment]
行政区划代码的结构里有很多特殊的内容，自行定义数据结构很可能出现应用异常，插件将来不出意外也不会支持自定义数据源
