### ISSUE TITLE
ts 情况下全局引入会报错，提示没有对应的声明文件

### ISSUE THREAD

**Issue by xiaofan9** [TerryZ/v-region#31]
![image](https://user-images.githubusercontent.com/16103130/104293476-0278e780-54f9-11eb-85fc-518992e2d6de.png)
建议提供下ts的支持

**Comment by TerryZ** [comment]
等 vue3 版统一处理吧

**Comment by xiaofan9** [comment]
> 等 vue3 版统一处理吧

建议vue3版支持下类似于 **_通过参数的方式自定义需要的数据_** 的功能，不然全局引入太多数据了，脑壳痛；

另：现在可以通过自行新建region.d.ts 声明文件解决报错；文件内容为：

```javascript
declare module 'v-region' {
  import vRegion from 'v-region'
  import _Vue from 'vue'

  export declare function install(Vue: typeof _Vue): void;

  export default vRegion;
}
```

**Comment by TerryZ** [comment]
是的，会考虑出一个三级行政区划的版本，四级的版本还是会保留
