### ISSUE TITLE
请问有没有计划更新一下数据源

### ISSUE THREAD

**Issue by Sanotsu** [TerryZ/v-region#32]
之前在使用时,可以看到有“广东东莞441900”和“中山442000”的镇级数据与一般的9位不同是12位(最后有未删尽的000);但"新疆-喀什-巴楚县-三岔口镇" 却为653130103001,不是9为且不是没删最后000而是001.

最近又看到有些区县下本来应该有镇级数据的,但实际是没有的,例如山东-济南-商丘,下面的没有镇级可选.

之前选用此组件也是欣喜有4位级联.我简单了解应该只需要更新下数据源等少量操作即可改善.我看本项目已经14个月未更新了,所以请问是否有此计划?谢谢.

**Comment by TerryZ** [comment]
有计划更新的，一方面是在等 Vue 3 正式版后进行重构，另一方面这么久没更新也跟疫情本身以及与之带来工作的繁忙，实际上不止是 `v-region` 我的其他项目基本也是差不多情况

**Comment by TerryZ** [comment]
已更新 `v2.3.0` 版本，全国 4 级行政区划数据更新至 `2022-05-18`
