### ISSUE TITLE
下拉列表的层级

### ISSUE THREAD

**Issue by Junesui** [TerryZ/v-region#34]
你好，点击下拉后，省市区选择框的 z-index 无法设置吗？
我用的dialog，点击选择后，省市区在dialog的下面，无法选择。

**Comment by TerryZ** [comment]
这类型具体项目适配问题，建议使用样式覆盖的方式来处理 `z-index`

**Comment by Soberuser** [comment]
我在draw里使用group也存在问题，框在draw里，框体本身能正常显示，下拉选择显示的内容在最底层的页面上，显示在draw下面。
div draw form RegionGroup 四级
对div的设z-index=1；draw设z-index=1；from设置z-index=999，或者from设置z-index=1， RegionGroup=999，RegionGroup框体本身都能正常显示，但下拉框还是在底层

**Comment by TerryZ** [comment]
通过浏览器的元素检查器，观察到内容都在下拉层容器里的，它是被追加到 body 根节点，一个 class 里包含 `v-dropdown-container` 的 div，其实你需要覆盖的样式就是将它的 z-index 的值进行调整，默认的值是 `3000`，它会显示在其他层以下，说明其他层的 `z-index` 比 `3000` 要大，在调试里逐步修改调整测试就行
