### ISSUE TITLE
请问什么时候更新最新的全国行政区划数据源？

### ISSUE THREAD

**Issue by ycywj** [TerryZ/v-region#41]
发现很多区县下面的乡镇、街道数据都不对，选不到对应的数据。能否支持自定义数据源呢？

**Comment by TerryZ** [comment]
已更新 `v2.3.0` 版本，全国 4 级行政区划数据更新至 `2022-05-18`

**Comment by ycywj** [comment]
***@***.***里面如何传递自定义的参数？ 除了获取当前选中的值，我还要传入当前组件在for循环里面的下标
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月21日(星期六) 凌晨1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TerryZ/v-region] 请问什么时候更新最新的全国行政区划数据源？ (Issue #41)





 
已更新 v2.3.0 版本，全国 4 级行政区划数据更新至 2022-05-18
