### ISSUE TITLE
如何在@values 传入自定义的参数？ 比如循环的下标

### ISSUE THREAD

**Issue by ycywj** [TerryZ/v-region#49]
如何在@values 传入自定义的参数？ 比如循环的下标

**Comment by TerryZ** [comment]
`@values` 事件（现已更名 `@change`）只是响应各级别变更的事情，只会输出数据，不接受输入数据

**Comment by ycywj** [comment]
我的意思是 比如 @change(item, index)  这种，支持自定义传递一个参数，我就好根据index来定位是那个标签这种

**Comment by TerryZ** [comment]
你说的是希望 `change` 事件能有一个数据项体现当前触发变更是哪一个行政级别的操作？

**Comment by ycywj** [comment]
不是，这个index可以是我自定义的，比如我传任意数，在方法里面能获取得到，就等于支持自定义参数

**Comment by ycywj** [comment]
好吧，是我理解错了。

**Comment by TerryZ** [comment]
```vue
<div v-for="(item, index) in list">
  <v-region
    @change="regionChange($event, index)"
  >
</div>
```

```js
function regionChange(data, index) {
  ...
}
```

这里举例界面上循环渲染了一个列表，每个项目里都包含了一个 `v-region`，那么在每一个 `v-region` 的 `change` 事件里指定的 `$event` 就是代表了事件原生输出的数据，第二个入参就是这个循环的下标 `index`，为一个插件外部的变量

参考 [vue2 官方文档-事件处理-内联处理器中的方法](https://v2.cn.vuejs.org/v2/guide/events.html#%E5%86%85%E8%81%94%E5%A4%84%E7%90%86%E5%99%A8%E4%B8%AD%E7%9A%84%E6%96%B9%E6%B3%95)

**Comment by ycywj** [comment]
好的，感谢指导
