### ISSUE TITLE
有面板收起事件吗

### ISSUE THREAD

**Issue by uCloudCastle** [TerryZ/v-region#50]
我用的RegionGroup，用户点击每一级行政区都会产生一个 change 事件，而且用户可以选择任意级别行政区。我们希望在用户完成他的选择之后（面板收起）再进行动作而不是 每次change 都执行，查看文档没找到对应的事件消息，请指教，多谢！

**Comment by TerryZ** [comment]
还是应该用变量来保存 `change` 事件输出的数据，在所有级别都选择完成，并自动收起面板后，会触发 `complete` 事件，你的应用可以在这个事件里进行统一把保存的数据赋值到表单或是什么数据集中

**Comment by uCloudCastle** [comment]
感谢回复！我们这边的场景是用户可以选择任意一级行政区，所以我们没办法判断用户是否完成了他的选择

**Comment by TerryZ** [comment]
在 v3 的版本增加了 `visible-change` 事件
