### ISSUE TITLE
使用之后组件空白

### ISSUE THREAD

**Issue by jeasonlyo** [TerryZ/v-region#56]
根据文档操作，页面上什么都没有显示，调试了之后，发现只有一层div其它都不见了不知道为啥。页面也没有报错

**Comment by jeasonlyo** [comment]
![image](https://user-images.githubusercontent.com/37092708/222152204-75f5ee9a-8154-45a3-9c25-e7f60a05afdb.png)
![image](https://user-images.githubusercontent.com/37092708/222152319-7413bca8-56b8-4813-979f-6b05da3ab106.png)
![image](https://user-images.githubusercontent.com/37092708/222152352-aa6d0eb7-bf8e-4164-a3c2-fd4173b2d243.png)

**Comment by TerryZ** [comment]
大概率你的表单是在弹窗里的，如果是的话，需要关注下和调试下弹出层的 `z-index` 有可能被弹出窗口覆盖了

**Comment by jeasonlyo** [comment]
没有在弹窗里面，但可以试试z-index，我看了示例的div有两个，但代码的div只有根那层div。

**Comment by jeasonlyo** [comment]
![image](https://user-images.githubusercontent.com/37092708/222159650-9c07e865-b182-4c75-8f8c-c3e71258efb4.png)
文档的示例

**Comment by TerryZ** [comment]
你的页面似乎有 3 个脚本错误，看看是不是有相关的内容

另外可以在 [CodePen](https://codepen.io/terry05/pen/ERNvzJ) 上对照着我的 demo 看看是不是有哪里没设置好

**Comment by TerryZ** [comment]
vue 的版本不能低于 2.6，目前 `v-region 2.x` 版本也不能在 vue3 生态上使用

**Comment by jeasonlyo** [comment]
确实是vue版本的问题谢了
