### ISSUE TITLE
省/直辖市、市 无法选择第二级

### ISSUE THREAD

**Issue by rawbin-** [TerryZ/v-region#6]
省/直辖市、市 
https://terryz.gitee.io/vue/#/region/demo
实例里面的第二个，选择北京，无法选择第二级

但先选一个其他省比如山西，然后再选一个城市，然后再选北京，就可以选北京的区了
希望一进来，就能实现这个效果

**Comment by TerryZ** [comment]
已在 v1.8.1 版本中修复该问题
