### ISSUE TITLE
RegionGroup 选择框有内容后文本后 清除按钮优化

### ISSUE THREAD

**Issue by Soberuser** [TerryZ/v-region#67]
RegionGroup 选择框有内容后点击文本后的清除按钮，源码中应该是span.rg-clear-btn，清除之后再次选择是在上次选择到的行政级别，比如选了省之后会主动跳到市，这时点清除下次打开还在市行政区，显示的是无匹配项。
点击下拉框后右上角有一个删除按钮，点了之后也会清除文本框里的内容，并且选择器会自动跳回第一级。
改进：选择框后面的span.rg-clear-btn按钮触发方法是clear，在clear方法中再调用一次那个删除按钮的方法，或者直接把文本框后触发的clear的方法改成下拉框右上角触发的方法，在源文件中没找到具体位置。

![ae15c8ecd04455d0d8af981f7de963bf](https://github.com/TerryZ/v-region/assets/58975141/69163b51-438e-47e2-8bfd-6fe71adec499)

**Comment by TerryZ** [comment]
该问题已发现并处理，因不影响功能使用，没有单独发版本的必要，会在后续功能更新一并升级

**Comment by TerryZ** [comment]
已在新版本中解决该问题
